
export const basic="https://backend-ecommerce-vwx4.vercel.app/api"
export const registerUrl="register"
export const LoginUrl="login"
export const LogOutUrl="logout"
export const usersUrl="users"
export const userUrl="user"
export const cat="category"
export const cats="categories"
export const pros="products"
export const pro="product"
export const latestSale="latest-sale"
export const topRated="top-rated"
export const latest="latest"
export const googleCallUrl="auth/google/callback"
export const cart="cart"
